# Generated by Django 3.1.7 on 2023-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('no_procesado', 'Not Processed'), ('procesado', 'Processed'), ('enviado', 'Shipping'), ('entregada', 'Delivered'), ('cancelada', 'Cancelled')], default='no_procesado', max_length=50),
        ),
    ]
