# Generated by Django 3.1.7 on 2023-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20231213_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('no_procesado', 'No Procesado'), ('procesado', 'Procesado'), ('enviado', 'Enviado'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='no_procesado', max_length=50),
        ),
    ]
